"""adding export table

Revision ID: e0efc322108e
Revises: 525306e5ea86
Create Date: 2025-09-04 15:50:25.584259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0efc322108e'
down_revision: Union[str, Sequence[str], None] = '525306e5ea86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('budgets_department_id_fkey'), 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'users', ['head_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('notification_preferences_user_id_fkey'), 'notification_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'notification_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('reports_generated_by_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['generated_by'], ['id'])
    op.drop_constraint(op.f('transactions_budget_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'budgets', ['budget_id'], ['id'])
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_budget_id_fkey'), 'transactions', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_generated_by_fkey'), 'reports', 'users', ['generated_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notification_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('notification_preferences_user_id_fkey'), 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(op.f('budgets_department_id_fkey'), 'budgets', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_table('export_history')
    # ### end Alembic commands ###
